version: '3.7'
services:
  reward-go-backend:
    container_name: reward_go
    image: golang:1.18-alpine
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - reward-backend
    environment:
      - app_name=go-reward
      - port=8080
    volumes:
      - ../:/app
    working_dir: /app
    command: go run cmd/gophermart/main.go

  reward-go-doc:
    container_name: reward_go_doc
    image: golang:1.18-alpine
    ports:
      - "${DOC_PORT}:${DOC_PORT}"
    networks:
      - reward-backend
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - reward-go-backend
    command: sh -c "go install -v golang.org/x/tools/cmd/godoc@latest && godoc -http=:${DOC_PORT}"

  reward-postgres:
    container_name: reward_postgres_container
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: "postgresql"
      POSTGRES_USER: "postgresql_user"
      POSTGRES_PASSWORD: "user_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql_user -d postgresql" ]
      timeout: 45s
      interval: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - reward-backend
networks:
  reward-backend:
    driver: bridge